### ISSUE TITLE
IR reply creates new incident

### ISSUE THREAD

**Issue by mnaylorwooster** [AdhocAdam/smletsExchangeConnector#1]
I'm not sure if I have misconfigured something, but when I reply to a ticket, your script creates a new IR. I've disabled my workflows so that is out of the mix. Any thoughts?

**Comment by AdhocAdam** [comment]
What work item type are you updating when this occurs? As unnecessary as it may sound (and of course without revealing any sensitive information), what does the email look like that is coming in look like? It contains a [IRxxxxxx] or [SRxxxxxx] style subject? Any special keywords in the body that this is possibly picking up? Off the top of my head, I know updating a Closed Incident with the [reactivate] keyword will trigger a new Incident. It may be related to this somehow?

If you could fill me in a bit more so I can attempt to repro I gladly will. My plan is to breakpoint the Update-WorkItem function and see how this may be getting caught inside of there,

**Comment by mnaylorwooster** [comment]
Actually, I think I may have it working. I changed the regex towards the end of the script where you parse each message. I took out the beginning and ending bracket matches. It now looks like this.

`"[I][R][0-9]+" {$result = get-workitem $matches[0] $irClass; if ($result){update-workitem $email "ir" $matches[0]} else {new-workitem $email $defaultNewWorkItem}}`

Is it the case that it was matching in the subject line but not when it looked up the incident?

**Comment by AdhocAdam** [comment]
Interesting as the regex you mention is what I _originally_ had in an early draft of this. However I eventually discovered that:

"[I][R][0-9]+"
Results in a match for IR1234


"\[[I][R][0-9]+\]"
Results in a match for [IR1234]

However I'm certainly into your line of thinking that the subject got matched, but not the lookup. I'll test and get back to you.

**Comment by AdhocAdam** [comment]
Sure enough, the update procedures send off the work item id with brackets instead of dropping them. As such, I've updated the Get-WorkItem function and the Update-WorkItem function calls respectively.

A sincere thanks.

**Comment by AdhocAdam** [comment]
After testing I was able to reproduce the issue and see to its resolution. As such I've marked this issue as Closed. If this is in error, please reply to this thread and I'll investigate further. Thanks again for reporting this!
