### ISSUE TITLE
Infinite loop on some emails during conversationID lookup

### ISSUE THREAD

**Issue by TomH-OpsDev** [AdhocAdam/smletsexchangeconnector#110]
**Describe the bug**
When certain (still in RCA--details to come, no obvious similarities yet) emails are processed by Update-WorkItem the script can get stuck in an infinite loop, outputting the same filter hundreds of times per minute (visible only if verbose/debug logging is turned on).

**Help us reproduce the bug**
Version of the connector you are using: 1.4.6
Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI): $createNewWorkItemWhenClosed = $true
$mergeReplies = $true

**Expected behavior**
An active ticket is updated or a new ticket is created based on whether the current email message matches any email attachments in the system with the same conversationID or not.

**Location and Environment**
Where are you running this from? Task Scheduler? SMA? Workflow server?: SMA 1807
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.):  SCSM 1807

**Additional context**

**Comment by TomH-OpsDev** [comment]
This appears to be occurring inside Update-WorkItem, when $CreateNewWorkItemWhenClosed == true and the work item is closed.  The next IF statement checks to see if there is an attachment out there with the same conversation ID, then if so, recursively invokes Update-WorkItem again.

More testing needed since this has happened (far less frequently) on workitems that are still open.  Debug and Verbose logging has not been helpful for pinpointing this...

Potential fix ideas:

- Add an optional param to Update-WorkItem that is true/false, and if set will just move to the "else" clause in this statement that calls Update-WorkItem on itself.  
- Check to see if the found ticket is also closed and if so just move to the "else" clause so Update-WorkItem is not called again.

**Comment by TomH-OpsDev** [comment]
Initial testing with the second choice worked on a problematic email that was saved.

**Comment by TomH-OpsDev** [comment]
Tested with more "problem emails" and they worked just as consistently as the were previously failing.  Have been testing this for several days without any failures.

Although in a perfect world I would like to run quite a few more tests to rule out other potential issues that may be lurking and causing similar behavior, this seems to have addressed all the issues I can currently test for.

**Comment by AdhocAdam** [comment]
To be released with #113
