### ISSUE TITLE
Vote on Behalf of an Active Directory Group

### ISSUE THREAD

**Issue by AdhocAdam** [AdhocAdam/smletsExchangeConnector#13]
Enable Users to Vote on Behalf of an Active Directory Group for Review Activities. The user of that group would then be set in the "Voted By" relationship for that Reviewer (i.e. the AD Group).

This feature like the many before it, would be enabled or disabled via a $true/$false in the initial configuration.

**Comment by AdhocAdam** [comment]
Within the RA Approve/Reject area of the switch on Update-WorkItem, planning to leverage something to the effect of -

`try {get-adgroup $reviewer; get-adgroupmember $reviewer} catch {<# reviewer is a user #>}`

**Comment by AdhocAdam** [comment]
Targeting v1.4

**Comment by TomH-OpsDev** [comment]
Critical functionality - I almost exclusively use groups instead of individuals in RA templates.  This is in my sub-branch and will be tested along with everything else.  If this gets updated further, I'll gladly test again after the pull.
