### ISSUE TITLE
Email Replies Not Parsing

### ISSUE THREAD

**Issue by moverton28** [AdhocAdam/smletsexchangeconnector#131]
Hi there, not sure if this is a bug or something I've misunderstood or not set correctly, hence why I've raised it as more of a question than an actual bug.

It revolves around the `$includeWholeEmail` and `$fromKeyword` settings.

I have tried 3 slightly different configurations, but all three yield the same result: the entire email chain (including everything after "From:", not just the reply, is added to the work item action log which I don't want.

Configuration 1:
`$includeWholeEmail = $true`
`$fromKeyword = "From"`

Configuration 2:
`$includeWholeEmail = $true`
`$fromKeyword = "From:"`

Configuration 3:
`$includeWholeEmail = $false`
`$fromKeyword = "From:"`

Which configuration is correct if I only want the reply to be added to the action log, rather than the full email chain?

**Comment by AdhocAdam** [comment]
They are all really close. What you're looking for is...

```powershell
$includeWholeEmail = $false
$fromKeyword = "From"
```

How the "From" keyword is configured here vs. the original connector is different in that you don't have to include the ":". My original thought behind this was having a more consistency between how one would define keywords without having to remember things like : or [], etc. Just type the word and done.

All of this said - it's not a lot of effort, so I'm already thinking this is worth accounting for within the connector via an enhancement request so as to prevent this scenario from happening in the future. Just another way of me saying thanks for the input :)

**Comment by moverton28** [comment]
Ah thank you! That explains it.

In that case, I think there might be an error in the comments that explain each setting. I can't remember exactly what it states for the `$fromKeyword` as I only have access to my phone this week and trying to view the code page on GitHub in my mobile browser crashes it...!

It was something similar to: If `$includeWholeEmail` is set to true, emails will be parsed UNTIL this keyword.

Shouldn't that be if it's set to false?

**Comment by AdhocAdam** [comment]
You are in fact correct sir.

https://github.com/AdhocAdam/smletsexchangeconnector/blob/5e488ed24ff9467e0a8691df56cc993eabfb9c7c/smletsExchangeConnector.ps1#L161

I'll get this updated.

**Comment by AdhocAdam** [comment]
Fixed and deployed to the dev branch. I've wrapped #132 into the next [milestone ](https://github.com/AdhocAdam/smletsexchangeconnector/milestone/5)for the release due end of June which will include this updated verbiage. Thanks again!
