### ISSUE TITLE
Approval Via AD Group Members

### ISSUE THREAD

**Issue by rameuses** [AdhocAdam/smletsexchangeconnector#134]
At times we want an entire AD Group to receive the RA approval request; so we add the AD Group as the reviewer rather than adding each member of the group separately. This allow us to manage the group via AD rather than changing the RA reviewers via the Request Offering template.

The notification gets sent as expected but neither the OOB Exchange Connector nor the SMLetsExchangeConnector will process a vote by a member of the group because ADGroup as Reviewer != ADGroupMember.

My feature request is for the SMLetsExchangeConnector to check whether the voter is a member of an AD group that is listed as the reviewer. If so, process the vote for that AD Group as reviewer.

**Comment by AdhocAdam** [comment]
Good news @rameuses - the SMlets Exchange Connecto _does_ support this! It was introduced in v1.4 as seen in the notes here:

https://github.com/AdhocAdam/smletsexchangeconnector/blob/5e488ed24ff9467e0a8691df56cc993eabfb9c7c/smletsExchangeConnector.ps1#L77

And configurable here:
https://github.com/AdhocAdam/smletsexchangeconnector/blob/5e488ed24ff9467e0a8691df56cc993eabfb9c7c/smletsExchangeConnector.ps1#L218

**Comment by rameuses** [comment]
@AdhocAdam - Amazing. Thankfully we're running 1.4.4 so turning it on was easy. I'm hoping to upgrade my dev environment to your alpha release soon. Thank you for sharing your great work!
