### ISSUE TITLE
Dynamic Analyst Assignment not working

### ISSUE THREAD

**Issue by AdhocAdam** [AdhocAdam/smletsexchangeconnector#135]
**Describe the bug**
No matter what the values are set to, random, volume, or OOO based. Dynamic assignment never actually assigns the new work item out the analyst.

**Help us reproduce the bug**
Version of the connector you are using: v1.5
Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI): $DynamicWorkItemAssignment = "random"

**Expected behavior**
Based on any of the allowed values, assign the work item out

**Comment by kenmcmi** [comment]
On 1.5
$defaultIRTemplateName = "SMLetExchangeConnector"
$DynamicWorkItemAssignment = "random"
$enableAzureCognitiveServicesForNewWI = $false

Template has a support group of Helpdesk

Helpdesk has an AD group mapped to it in the Service Manager console.

In the Cireson Portal - I can select members of the group to assign incidents too.

**Comment by AdhocAdam** [comment]
Looks like this is the issue right here:

https://github.com/AdhocAdam/smletsexchangeconnector/blob/5e488ed24ff9467e0a8691df56cc993eabfb9c7c/smletsExchangeConnector.ps1#L1767-L1770

Line 1770 should be using $SupportGroupID not $templateSupportGroupID

**Comment by kenmcmi** [comment]
I made the above change. tried both random and volume options but it is not assigning an analyst

thanks

**Comment by AdhocAdam** [comment]
Made another fix. Check out the latest change on the [pull](https://github.com/AdhocAdam/smletsexchangeconnector/pull/139/files)

**Comment by kenmcmi** [comment]
No luck - not getting any errors but no analysts are being assigned

**Comment by AdhocAdam** [comment]
Sounds like we need to do some actual function testing in your environment here:

There are 3 functions responsible for this feature -
- Get-TierMembers
- Get-AssignedToWorkItemVolume
- Set-AssignedToPerSupportGroup (this function is the one called from New-WorkItem after the Work Item has been created. It in turn calls the other two)

As seen here in the current Pull:
https://github.com/AdhocAdam/smletsexchangeconnector/blob/37ef336da344c20f8064c18a0ee04c527b9798c8/smletsExchangeConnector.ps1#L1728-L1787

I've modified the functions for the purposes of this test, but they honor the changes currently in the aforementioned pull. These modified versions will let you test functionality without assigning any Work Items. First the config section, the functions, and then their respective calls. Just enter the name of an Incident template and you're ready to run.

```powershell
#CONFIG
#first, let's retrieve an Incident Template that has Tier Queue (Support Group) defined on it.
#this Tier Queue must be defined within Cireson Support Group Mapping to an AD Group with members.
$IRTemplate = Get-SCSMObjectTemplate -display "your incident template display name goes here"
$domainUserClass = Get-SCSMClass -name "System.Domain.User$"
$assignedToUserRelClass = Get-SCSMRelationshipclass -name "System.WorkItemAssignedToUser"
$DynamicWorkItemAssignment = "random"

#FUNCTIONS
function Get-TierMembers ($TierEnumId)
{
    #define classes
    $mapCls = Get-ScsmClass -Name "Cireson.SupportGroupMapping"

    #pull the group based on support tier mapping
    $mapping = $mapCls | Get-ScsmObject  | ? { $_.SupportGroupId.Guid -eq $TierEnumId }
    $groupId = $mapping.AdGroupId

    #get the AD group object name
    $grpInScsm = (Get-ScsmObject -Id $groupId)
    $grpSamAccountName = $grpInScsm.UserName
    
    #determine which domain to query, in case of multiple domains and trusts
    $AdRoot = (Get-AdDomain -Identity $grpInScsm.Domain).DNSRoot

    if ($grpSamAccountName)
    {
        # Get the group membership
        [array]$supportTierMembers = Get-ADGroupMember -Server $AdRoot -Identity $grpSamAccountName -Recursive | foreach-object {Get-SCSMObject -Class $domainUserClass -filter "Username -eq '$($_.samaccountname)'"}
    }
    return $supportTierMembers
}

function Get-AssignedToWorkItemVolume ($SCSMUser)
{
    #initialize the counter, get the user's assigned Work Items that aren't in some form of "Done"
    $assignedCount = 0
    $assignedWorkItemRelationships = Get-SCSMRelationshipObject -TargetRelationship $assignedToUserRelClass -TargetObject $SCSMUser 
    $assignedWorkItemRelationships = $assignedWorkItemRelationships | select-object SourceObject -ExpandProperty SourceObject | select-object -ExpandProperty values | ?{($_.type.name -eq "Status") -and (($_.value -notlike "*Resolve*") -and ($_.value -notlike "*Close*") -and ($_.value -notlike "*Complete*") -and ($_.value -notlike "*Skip*") -and ($_.value -notlike "*Cancel*"))}
    $assignedWorkItemRelationships | foreach-object {$assignedCount++}
    
    #build Assigned To Volume object
    $assignedToVolume = New-Object System.Object
    $assignedToVolume | Add-Member -type NoteProperty -name SCSMUser -value $SCSMUser
    $assignedToVolume | Add-Member -type NoteProperty -name AssignedCount -value $assignedCount
    return $assignedToVolume
}

function Set-AssignedToPerSupportGroup ($SupportGroupID)
{
    #get the template's support group members
    $supportGroupMembers = Get-TierMembers -TierEnumID $SupportGroupID

    #based on how Dynamic Work Item assignment was configured, set the Assigned To User
    switch ($DynamicWorkItemAssignment)
    {
        "volume" {$supportGroupMembers | foreach-object {Get-AssignedToWorkItemVolume -SCSMUser $_} | Sort-Object AssignedCount -Descending | Select-Object -first 1 | select-object displayname }
        "OOOvolume" {$supportGroupMembers | Where-Object {$_.OutOfOffice -ne $true} | foreach-object {Get-AssignedToWorkItemVolume -SCSMUser $_} | Sort-Object AssignedCount -Descending | Select-Object -first 1 | select-object displayname }
        "random" {$supportGroupMembers | Get-Random | select-object displayname }
        "OOOrandom" {$supportGroupMembers | Where-Object {$_.OutOfOffice -ne $true} | Get-Random | select-object displayname }
        default {<#the config variable has a value that wasn't part of the set#>}
    }
}

#PROCESS
#get the Support Group ID from the Template baed on it's property collection
$templateSupportGroupID = $IRTemplate | select-object -expandproperty propertycollection | where-object{($_.path -like "*TierQueue*")} | select-object -ExpandProperty mixedvalue

#call the Get-TierMembers function directly by passing the TierEnumID to it.
#this will retrieve the AD Group Relationship from the Cireson Portal Mappings MP, then query AD for that group,
#and finally retrieve the Users within that Group. The output should be a list of users.
$supportGroupMembers = Get-TierMembers -TierEnumId $templateSupportGroupID
$supportGroupMembers

#if the above returned a list of users, this function should now only return a single user of that group
Set-AssignedToPerSupportGroup -SupportGroupId $templateSupportGroupID
```

**Comment by AdhocAdam** [comment]
Just wanted to follow up and see if you've had a chance to test out the above modified functions.

**Comment by kenmcmi** [comment]
Sorry Adam

I didn’t even see the previous comment with the updated test options.

I will get that scheduled to test

Thanks!

**Comment by kenmcmi** [comment]
Here this are the errors

PS C:\scripts> C:\scripts\smletsExchangeConnectorOLD.ps1
Get-SCSMObject : Cannot bind argument to parameter 'Id' because it is null.
At C:\scripts\smletsExchangeConnectorOLD.ps1:1747 char:38
+     $grpInScsm = (Get-ScsmObject -Id $groupId)
+                                      ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-SCSMObject], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,SMLets.GetSMObjectCommand
 
Get-ADDomain : Cannot validate argument on parameter 'Identity'. The argument is null or an element of the argument collection contains a null value.
At C:\scripts\smletsExchangeConnectorOLD.ps1:1751 char:39
+     $AdRoot = (Get-AdDomain -Identity $grpInScsm.Domain).DNSRoot
+                                       ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-ADDomain], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.ActiveDirectory.Management.Commands.GetADDomain
 
Get-SCSMObject : Cannot bind argument to parameter 'Id' because it is null.
At C:\scripts\smletsExchangeConnectorOLD.ps1:1747 char:38
+     $grpInScsm = (Get-ScsmObject -Id $groupId)
+                                      ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-SCSMObject], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,SMLets.GetSMObjectCommand
 
Get-ADDomain : Cannot validate argument on parameter 'Identity'. The argument is null or an element of the argument collection contains a null value.
At C:\scripts\smletsExchangeConnectorOLD.ps1:1751 char:39
+     $AdRoot = (Get-AdDomain -Identity $grpInScsm.Domain).DNSRoot
+                                       ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-ADDomain], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.ActiveDirectory.Management.Commands.GetADDomain
 
Get-Random : Cannot validate argument on parameter 'InputObject'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\scripts\smletsExchangeConnectorOLD.ps1:1786 char:42
+         "random" {$supportGroupMembers | Get-Random | select-object displayname  ...
+                                          ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Random], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.GetRandomCommand

**Comment by AdhocAdam** [comment]
The very first error message tends to imply that the Support Group used in the Default Work Item template set by the SMLets Exchange Connector is not mapped to an AD group in the Cireson Support Group Mapping. But don't worry, I'm not letting myself off the hook that easy 😁 

So let's run the following. All you need to do is change the first variable to the display name of the Support Group featured on the Default Work Item template being applied by the SMLets Exchange Connector. Technically speaking, this _is not_ the most efficient way to retrieve the Enum but it's the easiest to share/explain for this purpose.
```powershell
$defaultSupportGroup = "Level 1"
Get-SCSMEnumeration | ?{$_.displayname -eq "$defaultSupportGroup"} | select displayname, id
```

That should return the ID/GUID of the Support Group. Plug that GUID into the last statement below that calls the Get-TierMembers function.


```powershell
function Get-TierMembers ($TierEnumId)
{
    #define classes
    $domainuserClass = Get-SCSMClass -name "system.domain.user$"
    $mapCls = Get-ScsmClass -Name "Cireson.SupportGroupMapping"

    #pull the group based on support tier mapping
    $mapping = $mapCls | Get-ScsmObject  | ? { $_.SupportGroupId.Guid -eq $TierEnumId }
    $groupId = $mapping.AdGroupId

    #get the AD group object name
    $grpInScsm = (Get-ScsmObject -Id $groupId)
    $grpSamAccountName = $grpInScsm.UserName
    
    #determine which domain to query, in case of multiple domains and trusts
    $AdRoot = (Get-AdDomain -Identity $grpInScsm.Domain).DNSRoot

    if ($grpSamAccountName)
    {
        # Get the group membership
        [array]$supportTierMembers = Get-ADGroupMember -Server $AdRoot -Identity $grpSamAccountName -Recursive | foreach-object {Get-SCSMObject -Class $domainUserClass -filter "Username -eq '$($_.samaccountname)'"}
    }
    return $supportTierMembers
}

Get-TierMembers -TierEnumId "00112233-4455-6677-8899-aabbccddeeff"
```

The output of this _should be_ a list of AD users. If that works, that leads me to believe a Support Group isn't set on the Default Template the connector is using. If is returns nothing and/or errors like you've shared above it suggests a Mapping isn't complete.

**Comment by kenmcmi** [comment]
That worked as expected

It returned the members of the group

**Comment by AdhocAdam** [comment]
Upon some rather detailed inspection/referencing your observed behavior (e.g. the single, very scoped success) I've managed to repro consistently and recently updated the branch with the said changes.

Let me know when you have a chance to test out the AdhocAdam-DynAnalystAssign branch.

**Comment by AdhocAdam** [comment]
Just wanted to follow up again on this to see if you've had a chance to test the branch/fixes out.

**Comment by AdhocAdam** [comment]
Still out there @kenmcmi ?

**Comment by AdhocAdam** [comment]
Currently aiming for end of September release of the next version via #138 . After testing of both random and volume based features, I can no longer repro the error as observed in your original case or subsequent ones.

I'm going to mark this as Closed to prepare for the final pull from dev to master. If this is in fact not resolved for the next version, please raise a new Issue.

**Comment by kenmcmi** [comment]
Thank you

I’ll test as soon as it comes out
