### ISSUE TITLE
Get-TemplatesByMailbox: incorrect variable name ($scsmEmail)

### ISSUE THREAD

**Issue by TomH-OpsDev** [AdhocAdam/smletsexchangeconnector#175]
**Describe the bug**
A variable, $scsmEmail, is used in the Get-TemplatesByMailbox function, where $workflowEmailAddress should have been used instead.

**Help us reproduce the bug**
_Version of the connector you are using_: 1.4.6
_Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI)_: $useMultipleMailboxes

**Expected behavior**
_A clear and concise description of what you expected to happen._
The Get-TemplatesByMailbox function will work as designed for all users.

**Location and Environment**
_Where are you running this from? Task Scheduler? SMA? Workflow server?_: SMA
_What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.)_: 2019

**Additional context**
[https://community.cireson.com/discussion/comment/20850#Comment_20850](https://community.cireson.com/discussion/comment/20850#Comment_20850)

**Comment by AdhocAdam** [comment]
**Workaround**
In the Get-TemplatesByMailbox function, replace the $scsmEmail variable with $workflowEmailAddress

**Comment by AdhocAdam** [comment]
To be released with #180 and #181
