### ISSUE TITLE
Not sure if it's a bug: trouble approving Review Activities

### ISSUE THREAD

**Issue by castaner** [AdhocAdam/smletsexchangeconnector#186]
**Describe the bug**
Using the old exchange connector I could approve RA's via email with no issues. 
Using [Approved] it would approve the RA and go to the next step.

**Help us reproduce the bug**
Create an RA and try to approve via email. v1.7

**Expected behavior**
In the old version it would update the RA and approve it and go to the next activity in the Change request

**Location and Environment**
SCSM 2019

**Additional context**

**Comment by AdhocAdam** [comment]
I'll check this out @castaner.

**Comment by castaner** [comment]
Thanks I appreciate it. It approves ok via the web but just not via email.

________________________________

**Comment by AdhocAdam** [comment]
Before I get lost in a rabbit hole trying to repro - Can you share anything about the emails, domain, and/or verify the following:

- The user attempting to approve, is not only a Reviewer on the Review Activity, but that the User in question has an email on their User object in SCSM that matches the address the approval email came from.
    - related to this, are you in a single or multi-domain environment? If multi then all the more reason to confirm the above

- Is it all Review Activities or some subset?

- While I assume the email is something like "I [approved] this" would you mind sharing that content?

- You said "the old version" are you referring to the original Microsoft connector? or a previous version of this one?

**Comment by castaner** [comment]
*   The user attempting to approve, is not only a Reviewer on the Review Activity, but that the User in question has an email on their User object in SCSM that matches the address the approval email came from. Yes
     *   related to this, are you in a single or multi-domain environment? Single Domain
  *   Is it all Review Activities or some subset?

So far since this is a dev box it’s the first one I am testing. I was working on approving stuff via the portal and it works. I will be testing MA’s via email as well once I get the RA going.

  *   While I assume the email is something like "I [approved] this" would you mind sharing that content?

[cid:image003.jpg@01D64656.6D162D30]

  *   You said "the old version" are you referring to the original Microsoft connector? or a previous version of this one?
The original exchange connector from MS(v3.1 I think or the latest they have) which is running on SCSM 2012.  We are migrating to SCSM 2019 with a clean install.

I am heading out but can give you more answers later tonight.

Thanks,

Rob

**Comment by AdhocAdam** [comment]
Sounds good! Look forward to further discussion on this.

**Comment by castaner** [comment]
Ok back. Let me know what else you need as an example?

Thanks,

Rob

Sent from my iPhone

On Jun 19, 2020, at 4:29 PM, Adam <notifications@github.com> wrote:

﻿

INX WARNING: external source email.

Sounds good! Look forward to further discussion on this.

**Comment by AdhocAdam** [comment]
It looks like github's email connector didn't parse the screenshot in the above thread. Could you add/edit that in? But in whichever case, I think I have enough details to try this out in v1.7.

If I need anything else I'll let you know and if you find any new things just post them back here.

**Comment by castaner** [comment]
![image](https://user-images.githubusercontent.com/47833512/85212484-defe0d80-b318-11ea-9c29-dbec5a2858a5.png)

**Comment by AdhocAdam** [comment]
Thanks!

**Comment by AdhocAdam** [comment]
In short - I can't seem to repro this. BUT!

I've tried this in 1.7 and on. I've also gone through the commit history and the Review Activity logic hasn't changed in quite some time. The last change to RA logic (I believe) was made was in 1.4 when Voting on Behalf of an AD Group was introduced. While this was an extension to the overall RA logic, it did in fact introduce a change in that the Active Directory PowerShell module was brought into play as this was used to evaluate if Reviewer(s) on the RA were a User or a Group.

That said, if the AD Module is not co-located where you're running the connector. I suspect that line 1585 as seen below would fail and thus bomb out of the if logic. Thereby no action is taken on the RA, but the connector would continue to process the next mail item.
https://github.com/AdhocAdam/smletsexchangeconnector/blob/2d0457c9bd2855c56d5477a48211717427be3cc7/smletsExchangeConnector.ps1#L1572-L1614

Can you confirm the AD modules presence? Apart from this I was using v1.0 of the SMLets module and PowerShell v5.1

**Comment by castaner** [comment]
Good morning

When you ask for AD module I am going to assume you are asking about the AD Connector:

[cid:image003.jpg@01D64E03.900C9360]

[cid:image005.jpg@01D64E03.900C9360]

I am using PSVersion 5.1
SMLets V1

So I also test it using an MA and it worked for that:
[cid:image009.jpg@01D64E03.900C9360]

I manually approved the RA to get to the next step.  Then tried [completed] via email with no issues.

Does that help with the AD connector part? It should work the same for MA’s and RA’s right?



Thanks,

Rob

**Comment by castaner** [comment]
![SCSM1](https://user-images.githubusercontent.com/47833512/86028421-789f7c00-b9f7-11ea-8eb3-1529bd8ea7b5.JPG)

**Comment by AdhocAdam** [comment]
No - when I'm referring to the AD Module, I mean the Active Directory PowerShell module. This is part of RSAT (Remote System Adminstration Toolkit) available through Windows Server Manager underneath Features.

**Comment by castaner** [comment]
I totally forgot to install that when I went through the instructions. Ugh
https://cireson.com/blog/cireson-support-deploys-open-source-smlets-based-exchange-connector/
Sorry about that. It’s working via email now.

Thanks and sorry for the waste of time.

Rob

**Comment by AdhocAdam** [comment]
Excellent! No problem whatsoever @castaner. I'm just glad I could help straighten things out.
