### ISSUE TITLE
logging feature

### ISSUE THREAD

**Issue by mnaylorwooster** [AdhocAdam/smletsexchangeconnector#2]
I couldn't find a place to submit a feature, so I put it here.
I'm currently trying to troubleshoot why a particular IR (via email) does not have an Affected User. I thought if there was some logging I could track down the point of the problem. Do you have any plans for logging options?

**Comment by AdhocAdam** [comment]
I'm not sure a better place to put this yet either, so in the interim I've marked this as an enhancement. However, this is absolutely something we want to do but were unsure what kind of logging we'd want until this started reaching others besides ourselves (see [here](https://community.cireson.com/discussion/2471/an-smlets-based-exchange-connector)). So...glad to have you here!

In short, the idea was to leverage the identical Registry Key that the Exchange Connector uses to figure out how verbose to get with logging. That said, discussion is entirely open on what those levels of logging would be. Per the link, I want to make it easily searchable (with PowerShell), filterable (within Event Viewer), and far more decipherable than the stock logging. It's just a question of _what_ should that logging look like?

I'm thinking something like this:
"Updated XX####### from AffectedUser with Comment. isprivate = false"
"Created Work Item XX###### for AffectedUser"
"Created Work Item XX######, Affected User of $emailAddress could not be found in your CMDB"


Again - very open to discussion on this so let's use this thread as a way to get ideas out in the open.

**Comment by saitoh183** [comment]
Feathub is what you need

**Comment by AdhocAdam** [comment]
Currently available on the dev branch and [v3.0.0-Beta1](https://github.com/AdhocAdam/smletsexchangeconnector/releases/tag/v3.0.0-Beta1). Create pull requests for the New-SMExcoEvent function to add further logging throughout. Relating over to #209
