### ISSUE TITLE
Attached Emails all have the same name

### ISSUE THREAD

**Issue by castanerINX** [AdhocAdam/smletsexchangeconnector#200]
**Describe the bug**
All email attachments show up as "message.eml"

**Help us reproduce the bug**
Version of the connector you are using: 1.7
Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI):

**Expected behavior**
Should show the subject of the email instead.

**Location and Environment**
Where are you running this from? Task Scheduler? SMA? Workflow server?: Task scheduler
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.): 2019 10.19.1035.0

**Additional context**
When exporting files using powershell to download the attachments if all emails show up as message.eml there is only one file instead of many depending on what's being attached.
![serivcemanager](https://user-images.githubusercontent.com/68913895/88684739-c7a20500-d0ba-11ea-8ab2-170bf8f413fa.JPG)

**Comment by AdhocAdam** [comment]
Hey there @castanerINX. This was originally done so as to meet parity to the original Microsoft Exchange Connector, not saying it can't get changed just wanted to share the original reason first.

Never the less, that is certainly an interesting point you raise!
- If it was the File Name of the email was the subject instead of "message.eml" would they all not be the same as well? if not near the same?
    - if you have "Merge Replies"enabled I could see how it's possible they could be different
    - if you don't have Merge Replies enabled, then I feel like you're counting on everyone changing the subject but always keeping the [Work Item] in the subject.

Whichever the case. Let's say I were to have 27 emails on an Incident.  _Even if_ the Subject was there, I would think those 27 emails fall into about 4-6 different groups.
- A New Incident [IR1234] has been created for you
- RE: A New Incident [IR1234] has been created for you
- Printer Broken [IR1234]
- RE: Printer Broken [IR1234]
- Follow up on [IR1234]
- RE: Follow up on [IR1234]

In this case, I think you'd still end up with only 4-6 emails instead of 27. So my next thought would be, why not change the filename during your export to be something more unique like
- email-WorkItemID-AttachedDAY-HOUR-MINUTE-SECOND
- email-WorkItemID-AttachedByLastName-AttachedDay-HOUR-MINUTE-SECOND

**Comment by castanerINX** [comment]
Yes I think you are right. We will need to change the name either based on the date or time of the export.

I guess there are trade off’s since the old Exchange Connector had it show the name of the email. If someone replied and it had the same subject line then it would add a (2) or (3) next to it. Either way I think I can modify the script to export the files from SM and adjust it by using the date or time stamp.

Thanks,

Rob

**Comment by AdhocAdam** [comment]
If you need some help feel free to paste the PowerShell here. Otherwise I'll mark this as resolved and plan to close in the next day or so.

Thanks for using the connector!

**Comment by castanerINX** [comment]
I have 2 scripts running but if you could help me with this one I can adjust the change request version. I do appreciate it.

Thanks,

Rob

**Comment by AdhocAdam** [comment]
Sure thing. So let's go for something similar to the examples I originally listed out.
- email-WorkItemID-AttachedDAY-HOUR-MINUTE-SECOND
- email-WorkItemID-AttachedByLastName-AttachedDay-HOUR-MINUTE-SECOND

This section that is actually doing the file processing...

```powershell
#For each file, archive to entity folder
if($files -ne $Null)
{
    #Create archive folder
    $nArchivePath = $ArchiveRootPath + "\" + $Emo.Id
    New-Item -Path ($nArchivePath) -ItemType "directory" -Force|Out-Null

    $files|%{
            Try
            {
                $_.DisplayName
                $fs = [IO.File]::OpenWrite(($nArchivePath + "\" + $_.DisplayName))
                $memoryStream = New-Object IO.MemoryStream
                $buffer = New-Object byte[] 8192
                [int]$bytesRead|Out-Null
                while (($bytesRead = $_.Content.Read($buffer, 0, $buffer.Length)) -gt 0)
                {
                    $memoryStream.Write($buffer, 0, $bytesRead)
                }
                $memoryStream.WriteTo($fs)
            }
            Finally
            {
                $fs.Close()
                $memoryStream.Close()
            }
    }
}
```

Would need to become...
```powershell
#For each file, archive to entity folder
if($files -ne $Null)
{
    #Create archive folder
    $nArchivePath = $ArchiveRootPath + "\" + $Emo.Id
    New-Item -Path ($nArchivePath) -ItemType "directory" -Force|Out-Null

    $files|%{
            Try
            {
                $_.DisplayName
                $attachedByDisplayName = (Get-SCSMRelationshipObject -BySource $_).TargetObject | Select DisplayName
                $addedDate = $_.AddedDate.ToShortDateString().Replace("/","-") + $_.AddedDate.ToShortTimeString()
                $fs = [IO.File]::OpenWrite(($nArchivePath + "\" + $_.DisplayName + "-" + $Id + "-" + $attachedByDisplayName + $addedDate))
                $memoryStream = New-Object IO.MemoryStream
                $buffer = New-Object byte[] 8192
                [int]$bytesRead|Out-Null
                while (($bytesRead = $_.Content.Read($buffer, 0, $buffer.Length)) -gt 0)
                {
                    $memoryStream.Write($buffer, 0, $bytesRead)
                }
                $memoryStream.WriteTo($fs)
            }
            Finally
            {
                $fs.Close()
                $memoryStream.Close()
            }
    }
}
```

So in this case, two wholly new variables are built up and then used to further build out the file name. But the whole script as you've presented it is maintained and just extended with new functionality on the file name.
```powershell
$attachedByDisplayName = (Get-SCSMRelationshipObject -BySource $_).TargetObject | Select DisplayName
$addedDate = $_.AddedDate.ToShortDateString().Replace("/","-") + $_.AddedDate.ToShortTimeString()
$fs = [IO.File]::OpenWrite(($nArchivePath + "\" + $_.DisplayName + "-" + $Id + "-" + $attachedByDisplayName + $addedDate))
```

**Comment by castanerINX** [comment]
Thank you. I will test it tomorrow. I do appreciate the assistance.

Thanks,

Rob

**Comment by castanerINX** [comment]
[cid:image001.png@01D669AA.A3236150]

Tried it and am getting this error. I can go back to the old version and get the test.txt and 1 message.eml file.

[cid:image002.png@01D669AB.EBEE37B0]



Thanks,

Rob

From: Rob Castaneda
Sent: Thursday, July 30, 2020 5:01 PM
To: AdhocAdam/smletsexchangeconnector <reply@reply.github.com>; AdhocAdam/smletsexchangeconnector <smletsexchangeconnector@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [AdhocAdam/smletsexchangeconnector] Attached Emails all have the same name (#200)

Thank you. I will test it tomorrow. I do appreciate the assistance.

Thanks,

Rob

**Comment by AdhocAdam** [comment]
If you had a screenshot there, Github's email connector doesn't parse them/put them inline. Whichever the case I can test out the PowerShell.

**Comment by castanerINX** [comment]
![Capture2](https://user-images.githubusercontent.com/68913895/89226844-465ade80-d5a2-11ea-8f84-394c77ebb9ee.JPG)
![Capture](https://user-images.githubusercontent.com/68913895/89226851-4824a200-d5a2-11ea-9856-4547df7fb3d6.JPG)

**Comment by AdhocAdam** [comment]
Ahh I see the problem now. Converting the time to a string results in something like "1:27 PM". While the space isn't an issue, the colon in the filename is. I've also gone with UTC time as it's how SC stores datetime values to introduce more uniqueness to the filename. I also caught an issue with the DisplayName of the user who Attached the file.

Tested this and can confirm the variables work as expected/files actually output. Although you may want to re-arrange how the file name gets built, but I leave that to you to decide how you'd like the format!

```powershell
    #For each file, archive to entity folder
    if($files -ne $Null)
    {
        #Create archive folder
        $nArchivePath = $ArchiveRootPath + "\" + $Emo.Id
        New-Item -Path ($nArchivePath) -ItemType "directory" -Force|Out-Null

        $files|%{
                Try
                {
                    $_.DisplayName
                    $attachedByDisplayName = (Get-SCSMRelationshipObject -BySource $_).TargetObject | Select DisplayName -ExpandProperty DisplayName
                    $addedDate = $_.AddedDate.ToUniversalTime().ToString("yyyyMMddTHHmmssZ")
                    $fs = [IO.File]::OpenWrite(($nArchivePath + "\" + $_.DisplayName + "-" + $Id + "-" + $attachedByDisplayName + "-" + $addedDate))
                    $memoryStream = New-Object IO.MemoryStream
                    $buffer = New-Object byte[] 8192
                    [int]$bytesRead|Out-Null
                    while (($bytesRead = $_.Content.Read($buffer, 0, $buffer.Length)) -gt 0)
                    {
                        $memoryStream.Write($buffer, 0, $bytesRead)
                    }
                    $memoryStream.WriteTo($fs)
                }
                Finally
                {
                    $fs.Close()
                    $memoryStream.Close()
                }
        }
    }
```

**Comment by castanerINX** [comment]
Thanks it works like a charm.

Rob

**Comment by AdhocAdam** [comment]
Glad I could help. Thanks for using the connector!

**Comment by castanerINX** [comment]
Hi Adam - Just wanted to give you an update. I've been testing it and due to the way it saves the emails in Service Manager as message.eml I can't get the subject or title of the email to transfer over. We've determined that the auditors don't want to dig through multiple emails to find the correct one.  They want to see the subject/title and a timestamp. I have now is the name of the submitter and the timestamp which I thought might work.

If there is anyway that might be updated in the next version of the connector that would be great. Just wanted to let you know what we are encountering.

**Comment by AdhocAdam** [comment]
Well the good news is that the mechanism to pull an email from SCSM and then parse the actual object does exist over on the blog [here](https://adhocadam.github.io/smletsexchangeconnector/how-much-time-can-you-save-when-you-enable-merge-replies/). But requires some slight adaptation to the logic so we can read the File Attachment object in SCSM, read its contents, and then parse out the Subject property from the *.eml string.

With $email and regex you get get additional properties or just use the $emailSubject and drop it into the file name. Keep in mind that the $emailSubject here has no validation on it, so it's possible for a subject to contain characters that cannot exist in a filename.


```powershell
    #For each file, archive to entity folder
    if($files -ne $Null)
    {
        #Create archive folder
        $nArchivePath = $ArchiveRootPath + "\" + $Emo.Id
        New-Item -Path ($nArchivePath) -ItemType "directory" -Force|Out-Null

        $files|%{
                Try
                {
                    $_.DisplayName

                    #read the email into memory and parse out the Subject: via regex
                    $ms = New-Object System.IO.MemoryStream($_.Content.data,0,$_.Content.data.Length)
                    $email = [System.Text.Encoding]::ASCII.GetString($ms.ToArray())
                    $emailSubject = $email | select-string -pattern "Subject:.*" | foreach-object { $_.Matches } | select value -expandproperty value
                    $emailSubject = $emailSubject.replace("Subject:", "").Trim()

                    $attachedByDisplayName = (Get-SCSMRelationshipObject -BySource $_).TargetObject | Select DisplayName -ExpandProperty DisplayName
                    $addedDate = $_.AddedDate.ToUniversalTime().ToString("yyyyMMddTHHmmssZ")
                    $fs = [IO.File]::OpenWrite(($nArchivePath + "\" + $_.DisplayName + "-" + $Id + "-" + $attachedByDisplayName + "-" + $addedDate))
                    $memoryStream = New-Object IO.MemoryStream
                    $buffer = New-Object byte[] 8192
                    [int]$bytesRead|Out-Null
                    while (($bytesRead = $_.Content.Read($buffer, 0, $buffer.Length)) -gt 0)
                    {
                        $memoryStream.Write($buffer, 0, $bytesRead)
                    }
                    $memoryStream.WriteTo($fs)
                }
                Finally
                {
                    $fs.Close()
                    $memoryStream.Close()
                }
        }
    }
```

**Comment by castanerINX** [comment]
Thanks that should work. I will test it but the first attempt looks like it adds it properly. Much appreciated.

Thanks,

Rob
