### ISSUE TITLE
Could not assign date ,SMLets.NewSCSMObjectProjectionCommand

### ISSUE THREAD

**Issue by kirkcharlesworthcairns** [AdhocAdam/smletsExchangeConnector#218]
Script has been running perfectly for months, getting this error message about not assigning a date.
I've fiddled round with date time formats etc but nothing is coming to me.

Are you able to help? Below is the error output with the section of script below

New-SCSMObjectProjection : Simple object value was not the proper type.
At smletsExchangeConnector.ps1:2393 char:37
+ ... .Incident" {New-SCSMObjectProjection -Type "System.WorkItem.IncidentP ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (13/11/2020 12:52:12:DateTime) [New-SCSMObjectProjection], InvalidSimpleObjectValueException
    + FullyQualifiedErrorId : Could not assign date ,SMLets.NewSCSMObjectProjectionCommand

From:
    

    $Projection = @{__CLASS = "$($WIObject.ClassName)";
                    __SEED = $WIObject;
                    $CommentClassName = @{__CLASS = $CommentClass;
                                        __OBJECT = @{Id = $NewGUID;
                                            DisplayName = $NewGUID;
                                            ActionType = $ActionType;
                                            $propDescriptionComment = $Comment;
                                            Title = "$($ActionEnum.DisplayName)";
                                            EnteredBy  = $EnteredBy;
                                            EnteredDate = (Get-Date).ToUniversalTime();
                                            IsPrivate = $IsPrivate;
                                        }
                    }
    }
    
    #create the projection based on the work item class
    switch ($WIObject.ClassName)
    {
        "System.WorkItem.Incident" {New-SCSMObjectProjection -Type "System.WorkItem.IncidentPortalProjection$" -Projection $Projection @scsmMGMTParams}
        "System.WorkItem.ServiceRequest" {New-SCSMObjectProjection -Type "System.WorkItem.ServiceRequestProjection$" -Projection $Projection @scsmMGMTParams}
        "System.WorkItem.Problem" {New-SCSMObjectProjection -Type "System.WorkItem.Problem.ProjectionType$" -Projection $Projection @scsmMGMTParams}
        "System.WorkItem.ChangeRequest" {New-SCSMObjectProjection -Type "Cireson.ChangeRequest.ViewModel$" -Projection $Projection @scsmMGMTParams}
    }
}

**Comment by AdhocAdam** [comment]
SCSM version? SMlets version? Connector version? All Work Items or just Incidents?

**Comment by kirkcharlesworthcairns** [comment]
Hi Adam,

Sorry that’s my first ever issue submission.

I’m running 2019 10.19.1035.0
Connector version 3.0 with SMLets version 1.0.1.0

I only use incidents at the moment via the Cireson community portal.

Kind Regards,

Kirk

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AdhocAdam** [comment]
No worries Kirk, just wanted to get some more context before troubleshooting! Couple of other questions:
- How is this being run? Task Scheduler, SMA, Azure Automation, or SCSM Workflows?
    - I ask as I'm curious how you're capturing the above error message and if you get any other errors during execution
- Are you sure about the SMlets version? It should be either 1.0.2012.0 or 1.0.2016.0 but in this case it _should be_ 1.0.2016.0


I've just tested submitting a comment to a known Incident with:
- SCSM 2019 v10.19.1035.0
- SMLets 1.0.2016.0
- SMLets Exchange Connector v3.0 RC1 via Workflows

and it was added successfully

**Comment by kirkcharlesworthcairns** [comment]
Hi Adam,

The script is being run as a scheduled task, I noticed that peoples comments and replies were no longer going in the action log and instead they were being attached as emails.

I’ve checked in the Add/Remove Programs for the installed version, it says its 1.0.1.0
[cid:image001.png@01D6BC18.1167CA60]

I’ve run this command ‘Get-SMLetsVersion’ to output the below.

TargetProduct       : Microsoft System Center 2012 - Service Manager
WorkingCopyRootPath : C:/Users/Administrator/Documents/WindowsPowerShell/CodePlex/smlets
URL                 : https://smlets.svn.codeplex.com/svn/Main/Source/SMLets/SMLets
RepositoryRoot      : https://smlets.svn.codeplex.com/svn
RepositoryUUID      : e17a0e51-4ae3-4d35-97c3-1a29b211df97
Revision            : 74609
LastChangedAuthor   : unknown
LastChangedRev      : 70086
LastChangedDate     : 2012-02-04 00:41:25 -0800 (Sat, 04 Feb 2012)
IsPrivate           : True
Changes             : {M       WiX/SMLets.X86.msi, M       WiX/SMLets.msi}
SMCompiledVersion   : 7.5.1561.0
SMInstalledVersion  : 10.19.1035.0
SM2012              : True

I can log a new incident with the script no problem, its just replies.
I decided to manually run the script in case there was an error message displayed, that’s how I got the original output.

Kind Regards,

Kirk

**Comment by AdhocAdam** [comment]
Unfortunately Github's email connector isn't that great when it comes to parsing screenshots so I can't see the above. But never the less, the output here is interesting for a couple reasons:

- I went to my own Add/Remove programs and I in fact see 1.0.1.0 listed
- I ran "Get-Module smlets" and it shows 1.0.2016.0
- I ran Get-SMLetsVersion and pwsh threw that error I believe everyone has seen at least once to the effect of "that command doesn't exist"
- I ran "Get-Module smlets | select exportedcommands -expandproperty exportedcommands" and Get-SMLetsVersion is no where to be found in that list

Perhaps we have different versions? Have you previously/ever installed SMLets from the PowerShell gallery via Install-Module SMLets or the MSI via GitHub? If there is a different way you obtained it and could share that could help me attempt to reproduce this.

**Comment by kirkcharlesworthcairns** [comment]
Hi Adam,

It seems that you have just fixed my issue and probably something I should have checked first!

I’ve downloaded the latest SMLets MSI from Github, uninstalled my previous version and installed this latest version.

Manually run the script and I don’t get any error messages!
My comments go straight into the action log as expected.

I don’t know how I managed to download a March 2012 version of SMLets or know how it has been running fine until now.

Kind Regards,

Kirk

**Comment by AdhocAdam** [comment]
Huzzah! Most excellent to hear sir. Glad we could get this straightened out.

Thanks for using the connector!
