### ISSUE TITLE
Custom Events not loading

### ISSUE THREAD

**Issue by alexaxb** [AdhocAdam/smletsExchangeConnector#229]
**Describe the bug**
If I enter a filepath to a custom events ps1-file, the script fails with:
Command Invoke-After... was not found

**Help us reproduce the bug**
Version of the connector you are using: 3.0
Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI):

**Expected behavior**
If I change row 665 to load the custom events as a module instead as an expression, it works as expected.
Invoke-Expression $smexcoSettingsMP.FilePathCustomEvents -> Import-Module $smexcoSettingsMP.FilePathCustomEvents

**Location and Environment**
Where are you running this from? Task Scheduler? SMA? Workflow server?: Task Scheduler
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.):  2019

**Additional context**

**Comment by AdhocAdam** [comment]
In the Settings MP, define the path as...

. C:\pathtoevents\smletsExchangeConnector_customEvents.ps1

**Comment by alexaxb** [comment]
Yep, did that..
Won't Invoke-Expression just like Invoke-Command, just execute the code without keeping the functions in memory?

**Comment by AdhocAdam** [comment]
And it still did not work?

Originally the rationale I had at the time was:
- I would always be within the context of some function of the connector
- I wasn't passing parameters
- SMA/Azure Automation _could_ treat that differently

This is arguably a remnant of v1 days of the connector wherein you were dealing with 100% powershell and editing those values. That said, I suppose the case could be made here for maturing/altering this behavior in a PowerShell/Settings UI world

**Comment by alexaxb** [comment]
Nope, as soon as I enter the path to the customevents-file, the main script throws:
Invoke-BeforeConnect : The term 'Invoke-BeforeConnect' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

But if I load the customevents-file as a module, all is well.

**Comment by AdhocAdam** [comment]
Hrmmm. Just trying to figure out how to repro this. In my lab I have:
- SCSM 2019
- Logging at 4 which shows Custom Events being successfully loaded
- Running in a non US region
- Custom Events using Invoke-Expression
- Custom Events executing custom PowerShell as introduced in #224 and #226 

🤔

**Comment by alexaxb** [comment]
Weird..I have always had this issue since I tried the connector (2.4) the first time. What PS version are you running on your SCSM machine? Maybe it's an issue in older PS...

**Comment by AdhocAdam** [comment]
All testing, builds, etc. are performed on Windows PowerShell 5.1

**Comment by alexaxb** [comment]
Me too. If run the commands manually the same way as the script (invoke the file, then call one of the functions) I get the same result.
![image](https://user-images.githubusercontent.com/14937505/102637268-07df4e00-4156-11eb-9a52-5d4aeab6bee6.png)

**Comment by AdhocAdam** [comment]
![thinking](https://user-images.githubusercontent.com/6636040/102637483-b2864b00-411b-11eb-801d-79ec589a9a21.gif)

**Comment by alexaxb** [comment]
Hey Adam, I just noticed the dot in your comment 9th of december, and you are correct. If you dot-source the path in the settings, the functions load correctly!

**Comment by AdhocAdam** [comment]
This has been eating away at me throughout upgrades. I cannot begin to tell you how thoroughly satisfying it is to hear this.

I'm going to update the Custom Events documentation on the Wiki to cite this and then move forward with resolution.

**Comment by AdhocAdam** [comment]
Updated!

https://github.com/AdhocAdam/smletsexchangeconnector/wiki/Custom-Events-Examples#enabling-custom-events
