### ISSUE TITLE
Regional decimal symbol not accepted in numbers in textboxes

### ISSUE THREAD

**Issue by PeterMiklian** [AdhocAdam/smletsExchangeConnector#253]
**Describe the bug**
My _Control panel\Region_ setting uses _comma_ as decimal symbol.
Textbox in the _File Attachments_ section of _SMLets Exchange Connector Settings_ only accepts _dot_ as decimal symbol.
After saving current settings (_OK_ button) and reopening _comma_ (=regional setting) is shown as decimal symbol which prevents validation and saving of settings.
I have to change _comma_ to _dot_ to click _OK_ even if I made no changes.

**Help us reproduce the bug**
Version of the connector you are using: v3.0 RC1

**Expected behavior**
Accept decimal symbols according to regional settings in textboxes.

**Location and Environment**
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.): 2016 UR8

**Additional context**
![image](https://user-images.githubusercontent.com/76806408/103401642-fb8dc480-4b49-11eb-90f8-38bb322cc576.png)

**Comment by AdhocAdam** [comment]
This was actually addressed in #227 and released through #226. Just grab [v3.1](https://github.com/AdhocAdam/smletsexchangeconnector/releases/tag/v3.1) to sort this out 😄
