### ISSUE TITLE
OAuth Security String

### ISSUE THREAD

**Issue by borison89** [AdhocAdam/smletsExchangeConnector#285]
Hi!

what you think about feature:
add custom field "OAuth Security String" near TenantID / AzureApplicationID in "SMLets Exchange connector settings" console
and then add this property in powershell script?
block
```
if ($UseExchangeOnline) {
     #request an access token from Azure
     $ReqTokenBody = @{
     Grant_Type    = "Password"
     client_Id     = $AzureClientID
     Username      = $ewsUsername + "@" + $ewsDomain
     Password      = $ewsPassword
     Scope         = "https://outlook.office.com/EWS.AccessAsUser.All"
     ### Client_Secret = $ClientSecret

}
$response = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$AzureTenantID/oauth2/v2.0/token" -Method "POST" -Body $ReqTokenBody
```

**Comment by AdhocAdam** [comment]
So is the idea to alternatively use a Secret _instead of_ a username/password? In addition to a username/password?

In either case, is there a particular reason?

**Comment by borison89** [comment]
I think this is nice solution for simplification oauch2 in office365 exch

reason:
when we try to auth in office365 (with login/password (WF account) and TenantID / ApplicationID), reave error "The request body must contain the following parameter: 'client_assertion' or 'client_secret'."
I added "client_secret" in to script ps1, but this is bad solution

**Comment by AdhocAdam** [comment]
Ahh! I think you may have just confirmed something for me/found a gap in my documentation.

On the Azure App you registered for this, go to the "Authentication" tab, scroll down, and then where it says "Allow public client flows" flip that to "Yes". Let me know if you get the same results.

![Capture](https://user-images.githubusercontent.com/6636040/115889612-b4d61a00-a419-11eb-8e07-0d8e8b6fa0c8.PNG)

**Comment by borison89** [comment]
ooookay, this's working!
you need add this information to wiki =)

but I think,  this feature auth with "Client_Secret" may needed for some users

**Comment by AdhocAdam** [comment]
[365/OAuth documentation](https://github.com/AdhocAdam/smletsexchangeconnector/wiki/Configuration-Examples#scenario-3-exchange-onlineoffice-365-with-oauth) has been updated with the above screenshot.

There were a couple reasons I didn't go with the Secret Flow, but the biggest was I wanted to keep the identical authentication experience with the stock connector. In doing so, this would maintain the SMLets Exchange Connector spirit of enabling a super easy transition to significant feature gains _without_ having to reconfigure what is arguably the actual "setup" of the connector - authentication. In addition, it also keeps the configuration of Orchestrator connectivity the same as well.

All of that said - thank you for bringing this up and thanks for using the connector!
