### ISSUE TITLE
Connector fails to mark emails as read or move to deleted items

### ISSUE THREAD

**Issue by saravalkyrie** [AdhocAdam/smletsExchangeConnector#288]
**Describe the bug**
Fails to mark the email as read and/or delete from mailbox, leading to tickets being repeatedly created for the same email. 

**Help us reproduce the bug**
Version of the connector you are using: v3.3 - ManagementPack install. - Exchange OnPrem 2019.

Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI):
Use impersonation
Create users not found in CMDB
Attach email to work item
Move to deleted items after processing
Vote on behalf of AD Groups
Process meeting requests
Update work items missing
If work item to update is closed
Prevent PII from being saved
Change incident status based on who replied
All AI/Azure options disabled
Workflow enabled.
Logging level 4.

**Expected behavior**
Email is processed, marked as read and then deleted. - issue also occurs if delete mail after processing is not selected.

**Location and Environment**
Where are you running this from? Task Scheduler? SMA? Workflow server?: Workflow on primary SCSM Server.
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.): 2019 RTM - 10.19.1035.0

**Additional context**
SCSM Event Log:
A Windows Workflow Foundation workflow failed during execution.
 
Workflow Type: SMLets.Exchange.Connector.Resources.RunScript 

Workflow Identifier: 7bdb4c11-31b8-bf66-e2ef-54de5d109462 

Exception Type: System.Management.Automation.ParameterBindingValidationException 

Exception Message: Cannot bind argument to parameter 'Id' because it is null. 

Exception Stack:    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at SMLets.Exchange.Connector.Resources.RunScript.Execute(ActivityExecutionContext SMEXCOContext)
   at System.Workflow.ComponentModel.ActivityExecutorOperation.Run(IWorkflowCoreRuntime workflowCoreRuntime)
   at System.Workflow.Runtime.Scheduler.Run()

No error in the SMLets Exchange connector log.

**Comment by AdhocAdam** [comment]
I've historically seen this error come up as it pertains to Dynamic Analyst Assignment which was identified to have an issue several versions ago that has since been addressed.

The short of it - wholly custom Templates (not out of box SCSM Templates) must be used with the connector.

Do you happen to have that feature enabled? and/or are there any recent changes you've made that could help further isolate this?

**Comment by saravalkyrie** [comment]
Thanks,

That was the magic bit of info I was missing being new to the connector and SCSM. added bonus its fixed our SLO calculation issue as well. :)

**Comment by AdhocAdam** [comment]
HUZZAH!
