### ISSUE TITLE
irLowUrgency not defined correctly

### ISSUE THREAD

**Issue by rameuses** [AdhocAdam/smletsExchangeConnector#38]
On line 298, $irLowUrgency = Get-SCSMEnumeration -name "System.WorkItem.TroubleTicket.Impact.Low$" @scsmMGMTParams

should be $irLowUrgency = Get-SCSMEnumeration -name "System.WorkItem.TroubleTicket.UrgencyEnum.Low$" @scsmMGMTParams

As it is currently an error is thrown on line 466: 'New-SCSMObject : Could not fine 'Impact' in enumeration 'Urgency'.

**Comment by AdhocAdam** [comment]
Thank you for bringing this to our attention. This has now been addressed.
