### ISSUE TITLE
Probably wrong construction of login name for Exchange Online

### ISSUE THREAD

**Issue by ghost** [AdhocAdam/smletsExchangeConnector#420]
$password should not be part of test whether login name match email address pattern,

https://github.com/AdhocAdam/smletsexchangeconnector/blob/9bcd5844bc92810b552a2c1967bd591813161e5c/smletsExchangeConnector.ps1#L4406

**Comment by AdhocAdam** [comment]
Great catch! Would you mind raising a pull request?

**Comment by AdhocAdam** [comment]
Just following up again, can you raise a pull request for this?

**Comment by AdhocAdam** [comment]
Will ship via #401
