### ISSUE TITLE
Mail is not added to comment when over 4000 characters

### ISSUE THREAD

**Issue by pwahlmueller** [AdhocAdam/smletsExchangeConnector#456]
**Describe the bug**
We send a Mail with a message lenght over 4000 to the connector. The email is attached, but message is added as comment when the length of the message is under 4000 characters but not, when the length is over 4000 characters.

**Help us reproduce the bug**
Version of the connector you are using: 5.0.0.29
All general, including Attach Whole Email on Action log

**Expected behavior**
The comment will be added with a length of 4000 characters.

**Location and Environment**
It runs in the Task Scheduler? 
SCSM 2019

**Additional context**
-

**Comment by AdhocAdam** [comment]
This was caught a couple weeks back and #452 was raised for it. This will ship with the next release.

**Comment by AdhocAdam** [comment]
[v5.0.3.7](https://github.com/AdhocAdam/smletsexchangeconnector/releases/tag/v5.0.3.7) has been released that includes this fix
