### ISSUE TITLE
Can't Add Comments to Change Requests

### ISSUE THREAD

**Issue by InT-2k** [AdhocAdam/smletsExchangeConnector#488]
**Describe the bug**
As soon, as the connector tries to read a mail with [CR], [RA] or [MA] in subject it fails with this error:
`A Windows Workflow Foundation workflow failed during execution.
 
Workflow Type: SMLets.Exchange.Connector.Resources.RunScript 

Workflow Identifier: 7bdb4c11-31b8-bf66-e2ef-54de5d109462 

Exception Type: System.Management.Automation.CmdletInvocationException 

Exception Message: Projection 

Exception Stack:    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at SMLets.Exchange.Connector.Resources.RunScript.Execute(ActivityExecutionContext SMEXCOContext)
   at System.Workflow.ComponentModel.ActivityExecutorOperation.Run(IWorkflowCoreRuntime workflowCoreRuntime)
   at System.Workflow.Runtime.Scheduler.Run() <br> Please check!
`

After the crash the connector retries it after the set time, but crashes again. If this happens no newer mails would be imported too.

As soon as we remove the "bad" mail, the connector works fine again.

**Help us reproduce the bug**
Version of the connector you are using: 5.0.4.5
Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI):
M365 Mailbox ticket@ with an impersonation of servicedesk@
Multimailbox is active with ~20 entries

**Expected behavior**
If a mail cant be processed, newer mails should be processed and the "bad" wrong should be ignored
[CR] > adds text to action log
[MA] / [RA] ignore (there is no action log)

**Location and Environment**
Where are you running this from? Task Scheduler? SMA? Workflow server?: Workflows server
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.): 2022 

**Additional context**

**Comment by AdhocAdam** [comment]
I just want to be clear, the email has only [CR], [RA] or [MA] in the subject? Or it has [CRxxxxx], [RAxxxxx] or [MAxxxxx] in the subject where x is a number?

Also its worth calling out in the expected behavior section above that intentionally or accidentally adding comments to a MA/RA that _do not_ contain actionable keywords will add their comments the parent work item. This has been the case since the earliest days of the connector.
- Review Activities: https://github.com/AdhocAdam/smletsexchangeconnector/blob/02be0b1aed028647848c982e19ae5779c7596822/smletsExchangeConnector.ps1#L2204-L2221
- Manual Activities
    - https://github.com/AdhocAdam/smletsexchangeconnector/blob/02be0b1aed028647848c982e19ae5779c7596822/smletsExchangeConnector.ps1#L2270-L2277
    - https://github.com/AdhocAdam/smletsexchangeconnector/blob/02be0b1aed028647848c982e19ae5779c7596822/smletsExchangeConnector.ps1#L2301-L2303

**Comment by InT-2k** [comment]
Hello Adam,

thanks for the response. 

You are correct, its more than [MA]:
Example 1: [MA-775500] - CR-775498 - Description
Example 2: RE: [CR-774192] - Description

Its a greate idea to find the parent ticket and attach the data there.

I have tested this with a SR Parent and there it works perfect.

Maybe we have the issue in CR modul? 
The Example 2 failed today too. So the CR comment had not be added to the ticket

**Comment by AdhocAdam** [comment]
Awesome. Just wanted to verify. 👍 So the case is:

- Example Subjects include multiple patterns, but only one of interest is in [square brackets]
    - This should be fine. The connector uses regex to identify [square brackets]. Seems unlikely this is the issue
- Work Item patterns are custom
    - This should be fine/wraps back around to the previous point
- Adding comments to an RA/MA correctly appended to a Service Request
    - Just looking for clarity again, did you try this on a MA/RA that had a parent CR and it failed? Or you tried it just on a CR and that failed? Or did you try both, and they both failed?

If I assume the worst in the above case where a CR won't work at all, but the rest of the Work Items are fine. When you attempt to add a comment to a CR, is there anything of interest in the logs on the Workflow server of either:
- SMLets Exchange Connector _(make sure you have logging set to 4)_
- Operations Manager

**Comment by InT-2k** [comment]
Yes, only one pattern is  with [ ]. So the system has a clear information where to add the informations.
My test today was:
> [CR-778072] Test Mail 

The errors seems to be our Change Request Modul.
I tested the same cases with CR + RA / MA and SR + RA / MA. 

All variations of SR worked fine and added the data to the SR.
In CR all failed -  Its seems its no issue from the RA / MA.

I tested the same mail with the default scsm mail connector and the mail was correctly prosessed and the action log filled.
Also I added a comment per web gui / scsm console, but I see no bad things in the event logs.

If the smlets mail connector fails I have the error from my first post in the op man folder:

> Log: Operations Manager
> Source: Health Service Modules
> Event ID: 33880

> A Windows Workflow Foundation workflow failed during execution.
> Workflow` Type: `SMLets.Exchange.Connector.Resources.RunScript
> Workflow Identifier: 7bdb4c11-31b8-bf66-e2ef-54de5d109462
> Exception Type: System.Management.Automation.CmdletInvocationException
> Exception Message: Projection
> Exception Stack: at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
> at SMLets.Exchange.Connector.Resources.RunScript.Execute(ActivityExecutionContext SMEXCOContext)
> at System.Workflow.ComponentModel.ActivityExecutorOperation.Run(IWorkflowCoreRuntime workflowCoreRuntime)
> at `System.Workflow.Runtime.Scheduler.Run()

In the smlets folder i have:
>1. Successfully retrieved an OAuth token from 365
>2. Successfully connected to Exchange
>3. Filtering Mailbox on: (($_.ItemClass -eq "IPM.Note")) -and ($_.isRead -eq $false)
>4. Messages to Process: 1

Then it start from number 1 again.

Without the "bad" mail inside I get two more log entries 
>5: Processed: 1 of 1
>6: Processed 1 messages in:
 >   Minutes: 0.0862976833333333
  >  Seconds: 5.177861
   > Milliseconds: 5177.861

**Comment by AdhocAdam** [comment]
This certainly helps zero in as the "projection error" is rather telling and now sounds isolated to the [Add-ActionLogEntry](https://github.com/AdhocAdam/smletsexchangeconnector/blob/02be0b1aed028647848c982e19ae5779c7596822/smletsExchangeConnector.ps1#L2938-L3030) function and specifically the type projection used at the very end to create the comment. If you open up a PowerShell session on/to the workflow server with SMLets loaded. Do you receive output for the following command?

```powershell
Get-SCSMTypeProjection -Name "Cireson.ChangeRequest.ViewModel$"
```

**Comment by InT-2k** [comment]
Sorry, for the bad error message 🤷‍♂️

> Get-SCSMTypeProjection -Name "Cireson.ChangeRequest.ViewModel$" 
has no output. 

I believe its because we dont have only cireson auto close in our scsm. Everything else is from us or operaio (itnetx)

I´m not sure, if it helps, but we have this typeproctions with changerequest in title:
![image](https://github.com/user-attachments/assets/158773e2-83a0-493e-8b61-511ca4140594)

**Comment by AdhocAdam** [comment]
No need to apologize, that error message was key here!

In any case, this is 100% the issue. The Type Projection (Cireson.ChangeRequest.ViewModel) to write comments to Change Requests isn't present in your environment. It is made available once the Cireson Portal is installed. It's that Type Projection that contains the relationship between Change Requests and their Action Logs as seen below:

![image](https://github.com/user-attachments/assets/751541e5-2101-4b73-8c47-11eec3b8dc63)

If you have a Type Projection that offers this relationship, you can update the following line inside of Add-ActionLogEntry with that Type Projection.

https://github.com/AdhocAdam/smletsexchangeconnector/blob/02be0b1aed028647848c982e19ae5779c7596822/smletsExchangeConnector.ps1#L3028

Otherwise, you'll have to create a Type Projection that contains this relationship.

**Comment by InT-2k** [comment]
Hello Adam,

thanks for this info and the connector runs without errors.

I changed the **Cireson.ChangeRequest.ViewModel$** to **System.WorkItem.ChangeRequestPortalProjection$**

Now all [CR*] / [MA*] / [RA*] mails are prosessed without any error. The new mail had been added to the workitem
