### ISSUE TITLE
Notify Support Group of [take] Action

### ISSUE THREAD

**Issue by rameuses** [AdhocAdam/smletsexchangeconnector#57]
Something I hear about a lot is that when a support group gets notified of an assignment to the group; everyone in the group has to open the work item to find out if it's been taken or assigned yet. 

He're the idea: If someone uses the [take] command and it is successful, send an e-mail to the rest of the support group letting them know it's been 'taken.'

Logic to follow:
Notify Support Group of Take: true/false

**Comment by AdhocAdam** [comment]
Two things come to mind here:

1. **As an org level process** - just use Reply All during a [take] action. This would require no change to the connector and get people what they need immediately with just a little training. Alternatively, @TomH-OpsDev addressed this kind of ability to customize through #21. As such the smletsExchangeConnector_customEvents.ps1 file enables you to setup an action through the Invoke-AfterTake function. Thereby enabling you to write your own customizations that are preserved when upgrades to the connector are made. Perhaps the "hook" could be enhanced further to accept parameters?
2. **As an enterprise level process** - I see a few sides of this and with these points I'm not sure there is a way to keep everyone happy without someone having to create mailbox rules to filter the notifications thus somewhat leading back into the first point on customizing
   * _All_ Support Groups wanting it or some selectively wanting it
   * Some subset of analysts within a Support Group wanting it/others not

Either way, look forward to further discussion on this!

**Comment by AdhocAdam** [comment]
Hey there @rameuses. I know it's been awhile, but I figured I'd follow up on this. Did you go the way of introducing logic to the Custom Event's "Invoke-AfterTake" function or the Reply All route?

**Comment by AdhocAdam** [comment]
I haven't fully tested this, but I believe the following PowerShell leveraged through the use of the optional Custom Events script (_smletsExchangeConnector_customEvents.ps1_) via the Invoke-AfterTake function...

- Can address this request
- Enables custom messages and formatting that are preserved through upgrades of the connector
- Enables the opportunity for even deeper customization should select Support Groups want/not want to make use of the feature

```powershell
Invoke-AfterTake
{
    switch ($wiType)
    {
        "ir" {$supportGroupEnumToNotify = $workItem.TierQueue.Id}
        "sr" {$supportGroupEnumToNotify = $workItem.SupportGroup.Id}
        "ma" {$supportGroupEnumToNotify = $workItem.$prSupportGroupPropertyName.Id}
        "cr" {$supportGroupEnumToNotify = $workItem.$crSupportGroupPropertyName.Id}
        "pr" {$supportGroupEnumToNotify = $workItem.$maSupportGroupPropertyName.Id}
    }

    $currentSupportGroupId = Get-SCSMEnumeration -id $supportGroupEnumToNotify @scsmMGMTParams | select-object id -ExpandProperty id
    if ($currentSupportGroupId)
    {
        $mapCls = Get-SCSMClass -Name "Cireson.SupportGroupMapping" @scsmMGMTParams
        $supportGroupMapping = Get-SCSMObject -Class $mapCls -Filter "SupportGroupId -eq '$currentSupportGroupId'" @scsmMGMTParams
        $scsmADGroup = Get-SCSMObject -Id $supportGroupMapping.AdGroupId @scsmMGMTParams
        $scsmEmailObject = Get-SCSMRelatedObject -SMObject $scsmADGroup | Where-Object {$_.ChannelName -eq "SMTP"}

        Send-EmailFromWorkflowAccount -toRecipients $scsmEmailObject.TargetAddress -subject "[$($WorkItem.id)] was taken" -body "<b>$($WorkItem.Id)</b> was taken by $($commentLeftBy.DisplayName)" -bodytype "HTML"
    }
}
```

**Comment by AdhocAdam** [comment]
Closing this one out as I believe Custom Events offers the most flexibility on an org by org, Support Group basis. Will move to the Wiki to help organize.
