### ISSUE TITLE
Both End User Comment and Analyst Comment Created

### ISSUE THREAD

**Issue by rameuses** [AdhocAdam/smletsexchangeconnector#58]
When the user is both the Affected User and the Assigned User and they reply to an e-mail (take, acknowledge, comment), two action log entries are created. One is marked 'End User Comment' and the other is marked 'Analyst Comment'.  When the affected user and the assigned to user are the same:

Comments to Create when Affected User is Assigned To User: enduser, analyst, both

In my case, we'd only want to create the analyst comment. This has an impact on the #private usage.

**Comment by AdhocAdam** [comment]
Thanks for pointing this out.

Just thinking out loud here but I think a simple check for if the Assigned To/Affected User are the same before the switch statement, then just nulling one before the switch statement should do the trick.

**Comment by AdhocAdam** [comment]
With some further investigation on how the OOB Exchange Connector handles this scenario, the email is marked as a Public End-User Comment.

I think at the very least we'd want to mimic this behavior to match parity with the OOB Exchange Connector and thus address the bug, but open the possibility of an "override" of sorts through a separate FR.

**Comment by rameuses** [comment]
That makes sense. In this situation the affected user will see all private messages anyway. The main issue was the duplicate log entry; which has been addressed. Thank you!
