### ISSUE TITLE
Reactivate IR - Entry Log Type

### ISSUE THREAD

**Issue by rameuses** [AdhocAdam/smletsexchangeconnector#61]
Could we have the action log entry created as type (Record Activated) when an incident is reactivated? Currently the action log is marked (Analyst Comment).

**Comment by AdhocAdam** [comment]
Conceptually sounds doable. Just need to figure out how the Task is run that triggers that event on the Action Log.

**Comment by AdhocAdam** [comment]
After some further thought on this, it _should_ be fairly similar to how Analyst or End User comments are left. It just being a different type of Action Log entry.

This could open up some other interesting scenarios apart from the core of this request.
