### ISSUE TITLE
Custom Work Item prefixes

### ISSUE THREAD

**Issue by AdhocAdam** [AdhocAdam/smletsexchangeconnector#8]
Ability to use custom work item prefixes other than IR or SR as defined through the SCSM console Administration -> Settings area.

**Comment by rameuses** [comment]
This is something we're looking for. We use a DEV and TEST environment before implementing in PROD. The Dev system uses DEV-IR or DEV-SR and the test system uses TEST-IR or TEST-SR. This helps analysts and users quickly identify that the e-mails they get are from test/dev systems. 

Not a show stopper, but in order to test this connector we have to use the connector to create the work item so it doesn't append the DEV- or TEST-. This introduces confusion for users/analysts who are used to seeing the prefixes.

**Comment by rameuses** [comment]
Since the native exchange connector handles this situation; it might be better marked as a bug.

**Comment by rameuses** [comment]
Here's a function that neatly returns the prefix for each workitem type:

https://github.com/lazywinadmin/PowerShell/blob/master/SCSM-Get-SCSMObjectPrefix/Get-SCSMObjectPrefix.ps1

**Comment by rameuses** [comment]
I've never used GitHub so I don't know I would go about actually contributing to this project. I think the attached will handle custom Work Item Prefixes though. It seems to be doing it for me anyway. I don't use all of the functionality (like calendar appointments) so I haven't tested everything. It did create a work item with the correct prefix and the [take] worked correctly.

[smletsExchangeConnector.zip](https://github.com/AdhocAdam/smletsexchangeconnector/files/2077780/smletsExchangeConnector.zip)

**Comment by AdhocAdam** [comment]
No worries @rameuses , it's actually as simple as creating a Fork of the repo. This will create a duplicate smletsexchangeconnector repo on your account and then from there you can edit it as you see fit.

Once you've made the edits you'd like, you can submit a Pull Request. This is a request that you'd like to merge changes from _your_ repo into mine. The advantage of doing this is everyone can then see the differences between what exists in the "master" repo so to speak vs. yours. Plus you can earn some contributor brownie points :)

I actively encourage you to do this and make some mistakes. It's a great learning opportunity that everyone benefits from!

**Comment by TomH-OpsDev** [comment]
Just catching up--I think this is a really good idea, but I see it as a feature request, not a bug.  My rationale is that code that is there works as designed, but would be better with this suggestion.  Agree with @AdhocAdam 's suggestion, feel free to jump in and ~~break stuff~~ contribute!  :)

There are other examples of getting settings from SCSM already in this script, which are very similar to lazywinadmin's example.   So I do not think it would be a big effort to integrate this, and here is some validation of the approach.  Good stuff!

**Comment by rameuses** [comment]
All right, I'll give it go with this Feature Request then.

**Comment by AdhocAdam** [comment]
Hey @rameuses no pressure but I was thinking about wrapping up 1.4.4 in the very near future. Would this be of any disruption if you were working on this particular feature? I didn't see the fork, but I didn't want to assume either.

**Comment by AdhocAdam** [comment]
Sounds good. It's my plan to knock out #66 in the next day or so then move into review for the release.

**Comment by AdhocAdam** [comment]
Created 1.4.5 branch which as of this comment is a mirror of 1.4.4/master. If you fork the repo now @rameuses you'll get this new branch so you can start on the new ground floor.

**Comment by rameuses** [comment]
Thanks @AdhocAdam! I've created the fork, downloaded GitHub Desktop and cloned the repository to my desktop. So, progress I think. I'm hoping to make the changes this week yet.

**Comment by AdhocAdam** [comment]
This feature has just been deployed to an alpha/pre-release that is based on v1.4.6 introducing the single change for custom work item prefixes seen [here](https://github.com/AdhocAdam/smletsexchangeconnector/releases/tag/v1.4.7alpha).

Still reviewing, but otherwise appear to be on schedule for #113

**Comment by AdhocAdam** [comment]
To be released on #113 hopefully before the week is out.
