### ISSUE TITLE
Get-ScsmClassProperty error when using CR / MA support group enums

### ISSUE THREAD

**Issue by TomH-OpsDev** [AdhocAdam/smletsexchangeconnector#85]
**Describe the bug**
Get-SCSMClassProperty : A parameter cannot be found that matches parameter name 'classname'.
... $maSupportGroupPropertyName = (Get-SCSMClassProperty -classname "system ...
(same error with CR support group)

**Help us reproduce the bug**
Version of the connector you are using: 1.4.5
Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI):  MA Support Group, CR Support Group

**Expected behavior**
No errors, name of MA/CR Support Group property would be returned

**Location and Environment**
Where are you running this from? Task Scheduler? SMA? Workflow server?:  SMA
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.): 1807

**Additional context**
The following workaround is effective:

1. Move the if ($maSupportGroupEnumGUID) {} and if ($crSupportGroupEnumGUID) {} statements below / inside of the region where all the classes are assigned to variables

2. Change -ClassName to -Class, supply $maClass and $crClass to the respective calls

**Comment by AdhocAdam** [comment]
Addressing in upcoming v1.4.6 release via PRr #102 by dropping use of the Get-SCSMClassProperty and relying on the underlying SCSM SDK to pull these class extensions.
