### ISSUE TITLE
If SCSM Connection Fails: Attach-FileToWorkItem - Property 'Count' cannot be found on this object

### ISSUE THREAD

**Issue by TomH-OpsDev** [AdhocAdam/smletsexchangeconnector#86]
**Describe the bug**
Attach-FileToWorkItem - Property 'Count' cannot be found on this object ($existingAttachments.Count += 1).  $existingAttachments may not be populated or defined in all cases, so the .Count property cannot be accessed or assigned.  The $existingAttachmentsCount variable is already defined above, but not used.  Change references to $existingAttachments.Count to $existingAttachmentsCount.  Ensure that $existingAttachmentsCount = 0 if null/empty since null != 0.

**Help us reproduce the bug**
Version of the connector you are using: 1.4.5
Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI): File attachments to ticket

**Expected behavior**
Send email with attachment, have attachment added to ticket without errors.

**Location and Environment**
Where are you running this from? Task Scheduler? SMA? Workflow server?: SMA
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.):  1807

**Additional context**

**Comment by AdhocAdam** [comment]
This issue's resolution will be seen with the March 2019 release.
