### ISSUE TITLE
If SCSM Connection Fails: New-WorkItem error, when using multiple mailbox templates: $templatesForThisMessage evaluating empty

### ISSUE THREAD

**Issue by TomH-OpsDev** [AdhocAdam/smletsexchangeconnector#87]
**Describe the bug**
Multiple mailbox templates: $templatesForThisMessage evaluating empty when it should match AND still attempting to assign template from this obj, which fails. (no template applied, as a result)

**Help us reproduce the bug**
Version of the connector you are using: 1.4.5
Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI): $useMultipleMailboxes, 

**Expected behavior**
When mailbox is matched, the template specified for the matched mailbox and for the given work item type should be applied.

**Location and Environment**
Where are you running this from? Task Scheduler? SMA? Workflow server?: SMA
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.): 1807

**Additional context**
Workaround:

1. move the statement "$TemplatesForThisMessage = Get-TemplatesByMailbox $message" above the block that tests whether Azure Cog svcs is in use or not

2. For each work item type in New-WorkItem, change the "if ($UseMailboxRedirection -eq $true -And $TemplatesForThisMessage) {" statement to "if ($UseMailboxRedirection -eq $true -And $TemplatesForThisMessage.Count -gt 0) {"

**Comment by AdhocAdam** [comment]
Will be included on the next releases - #180 and #181
