### ISSUE TITLE
If SCSM Connection Fails: Existing attachment search in Verify-WorkItem does not handle null search results

### ISSUE THREAD

**Issue by TomH-OpsDev** [AdhocAdam/smletsexchangeconnector#88]
**Describe the bug**
Error msg: Get-SCSMRelationshipObject : Cannot bind argument to parameter 'ByTarget' because it is null.
 4th line in Verify-WorkItem function.  WORKAROUND: Wrap the line in an IF statement that tests whether $emailAttachmentSearchObject is null (e.g.: if ($emailAttachmentSearchObject) {})

Next statement tests that the prior two are not null, so this seems like a good permanent fix.

**Help us reproduce the bug**
Version of the connector you are using:
Features/variables you have enabled (i.e. $enableAzureCognitiveServicesForNewWI): multiple mailboxes

**Expected behavior**
Proceed with no errors when no prior related attachments are found.

**Location and Environment**
Where are you running this from? Task Scheduler? SMA? Workflow server?: SMA
What SCSM version are you running? (i.e. 2012R2, 2016, 2016 UR3, 1801, etc.): 1807 

**Additional context**

**Comment by AdhocAdam** [comment]
Will be included on the next releases - #180 and #181
