### ISSUE TITLE
Use File Attachment settings per Work Item type

### ISSUE THREAD

**Issue by AdhocAdam** [AdhocAdam/smletsExchangeConnector#9]
Support file amount and file size restrictions as defined in the Administration -> Settings area for Incidents, Changes, Service Requests, etc.

**Comment by AdhocAdam** [comment]
Using the following as the basis for this:

```
$irSettings = (Get-SCSMObject -Class (Get-SCSMClass -Name "System.WorkItem.Incident.GeneralSetting$" -computername $scsmMGMTServer) -computername $scsmMGMTServer)
$srSettings = (Get-SCSMObject -Class (Get-SCSMClass -Name "System.GlobalSetting.ServiceRequestSettings$" -computername $scsmMGMTServer) -computername $scsmMGMTServer)
$prSettings = (Get-SCSMObject -Class (Get-SCSMClass -Name "System.GlobalSetting.ProblemSettings$" -computername $scsmMGMTServer) -computername $scsmMGMTServer)
$crSettings = (Get-SCSMObject -Class (Get-SCSMClass -Name "System.GlobalSetting.ChangeSettings$" -computername $scsmMGMTServer) -computername $scsmMGMTServer)
$rrSettings = (Get-SCSMObject -Class (Get-SCSMClass -Name "System.GlobalSetting.ReleaseSettings$" -computername $scsmMGMTServer) -computername $scsmMGMTServer)
```

Each of these will pull the settings as defined in the Administration -> Settings area for each of those respective Work Items. Each of these variables/objects contain the properties such as maximum allowed attachments, attachment size, etc.

**Comment by TomH-OpsDev** [comment]
Added to 1.4b-TH branch in https://github.com/AdhocAdam/smletsExchangeConnector/commit/ac16bb66d9b45a5feb4d2893e7f1ddf30a2fb59b

Currently testing.
